INSERT into station values('HWH','Howrah','B','ER');
INSERT into station values('NDLS','New Delhi','B','NR');
INSERT into station values('CNB','Kanpur Central','B','NCR');
INSERT into station values('KYN','Kalyan Junction','B','CR');
INSERT into station values('PNBE','Patna Junction','B','ECR');
INSERT into station values('BZA','Vijaywada Junction','B','SCR');
INSERT into station values('BRC','Vadodara Junction','B','WR');
INSERT into station values('SBC','KSR Bengaluru Junction','B','SWR');
INSERT into station values('MAS','Chennai Central','B','SR');
INSERT into station values('CSTM','Mumbai CST','B','CR');
INSERT into station values('JHS','Jhansi','B','NCR');
INSERT into station values('NNR','Narayanpur','B','WR');
INSERT into station values('SRI','Salmari','B','SER');
INSERT into station values('BONA','Boinda','B','SER');
INSERT into station values('BDI','Bhadli','B','NR');
INSERT into station values('DGDG','Durgada Gate','B','NER');
INSERT into station values('BNKR','Banka Road Oa','B','SER');
INSERT into station values('SRP','Serampore','B','ECR');
INSERT into station values('BIC','Bichia','B','ER');
INSERT into station values('GVI','Garividi','B','NR');
INSERT into station values('AHH','Ahmadgarh','B','ECR');
INSERT into station values('BHBK','Bodhadi Bujrug','B','ECR');
INSERT into station values('DOH','Dhodra Mohar','B','WR');
INSERT into station values('PUNE','Pune Junction','B','SER');
INSERT into station values('FTS','Fatehpur Sikri','B','ER');
INSERT into station values('GRMT','Gur Market','B','SER');
INSERT into station values('BEM','Budaun','B','SER');
INSERT into station values('RBS','Rupbas','B','ECR');
INSERT into station values('BDM','Badami','B','ECR');
INSERT into station values('SBLT','Shribdrya Lathi','B','NER');
INSERT into station values('BCO','Bhachau','B','ECR');
INSERT into station values('GNU','Ganaur','B','NR');
INSERT into station values('UPD','Ulavapadu','B','ECR');
INSERT into station values('KVZ','Kavali','B','ECR');
INSERT into station values('BYS','Barsali','B','SER');
INSERT into station values('KJJ','Kodavaluru','B','NER');
INSERT into station values('KAT','Khatauli','B','ECR');
INSERT into station values('PER','Perambur','B','SR');
INSERT into station values('DBY','Digboi','B','ECR');
INSERT into station values('PNP','Panipat Junction','B','WR');
INSERT into station values('SBY','Solan Brewery','B','SER');
INSERT into station values('ASD','Ambasamudram','B','NR');
INSERT into station values('KAYR','Kayar','B','NER');
INSERT into station values('KVLS','Karakavalasa','B','SER');
INSERT into station values('NMM','New Misamari','B','CR');
INSERT into station values('BTJ','Bishnathganj','B','SER');
INSERT into station values('TUL','Tiraldih','B','WR');
INSERT into station values('GALA','Gunadala','B','WR');
INSERT into station values('KYI','Kalyani','B','ER');
INSERT into station values('KMJ','Kaimganj','B','SWR');
INSERT into station values('DRPH','Devri Ph','B','ECR');
INSERT into station values('PSV','Parsneu','B','NER');
INSERT into station values('GOH','Garot','B','SER');
INSERT into station values('RPZ','Ranapratapnagar','B','SR');
INSERT into station values('PTRU','Patratu','B','ECR');
INSERT into station values('KRSA','Kharsaliya','B','ECR');
INSERT into station values('KRHA','Korahia','B','WR');
INSERT into station values('DPUR','Depur Ph','B','ER');
INSERT into station values('PPI','Pipariya','B','SWR');
INSERT into station values('DINR','Divine Nagar','B','ECR');
INSERT into station values('STR','Satara','B','NER');
INSERT into station values('DRD','Dahanu Road','B','NER');
INSERT into station values('DHW','Dhariwal','B','NR');
INSERT into station values('TDH','Tindharia','B','ECR');
INSERT into station values('SIKR','Sikar Junction','B','ECR');
INSERT into station values('BTJL','Bhatkal','B','NR');
INSERT into station values('BFT','Bhabta','B','ECR');
INSERT into station values('SNTD','Santaldih','B','CR');
INSERT into station values('PEM','Peralam Jn','B','NR');
INSERT into station values('DS','Dasna','B','WR');
INSERT into station values('BMU','Bamhrauli','B','ECR');
INSERT into station values('BZG','Bilga','B','SWR');
INSERT into station values('KLJ','Kamalganj','B','SER');
INSERT into station values('BPK','Bhugaon','B','ECR');
INSERT into station values('NKR','Nimar Kheri','B','CR');
INSERT into station values('ALJN','Aligarh Junction','B','NER');
INSERT into station values('KEB','Karambeli','B','ECR');
INSERT into station values('MNO','Mehnar Road','B','ECR');
INSERT into station values('KKZ','Kottarakara','B','NER');
INSERT into station values('BJRI','Bijuri','B','NER');
INSERT into station values('BMSB','Bhimasar Bg','B','ER');
INSERT into station values('BTH','Bettiah','B','ER');
INSERT into station values('DAB','Dharmabad','B','NR');
INSERT into station values('GUNA','Guna','B','NR');
INSERT into station values('BARH','Barh','B','NR');
INSERT into station values('SRP','Serampore','B','CR');
INSERT into station values('ANPR','Anpara','B','SWR');
INSERT into station values('AXK','Asokhar','B','CR');
INSERT into station values('FTS','Fatehpur Sikri','B','SER');
INSERT into station values('CBZ','Churaibari','B','CR');
INSERT into station values('TCN','Tiruchendur','B','CR');
INSERT into station values('HMY','Harmuti','B','NER');
INSERT into station values('SLR','Salogra','B','ECR');
INSERT into station values('NBL','Nimbal','B','NER');
INSERT into station values('MQQ','Markahandi U Ht','B','NER');
INSERT into station values('BLQR','Bilaspur Road','B','NR');
INSERT into station values('BLSD','Balsamand','B','NER');
INSERT into station values('TOU','Telaprolu','B','ER');
INSERT into station values('IAA','Indara Junction','B','WR');
INSERT into station values('KPG','Kopargaon','B','SR');
INSERT into station values('GP','Raj Gangpur','B','ECR');
INSERT into station values('SPTR','Silapathar','B','NER');
INSERT into station values('SKTN','Shakti Nagar','B','WR');
INSERT into station values('BJO','Bijnor','B','NER');
INSERT into station values('VGN','Vangaon','B','WR');
INSERT into station values('PRI','Pathri','B','ECR');
INSERT into station values('SGUD','Siliguri','B','ECR');
INSERT into station values('JTW','Jaitwar','B','ECR');
INSERT into station values('DGR','Durgapur','B','ECR');
INSERT into station values('NAM','Namrup','B','ECR');
INSERT into station values('TLHR','Talcher','B','ECR');
