create database railway;
CREATE TABLE STATION
( STATION_ID            VARCHAR(6)    NOT NULL,
  NAME                  VARCHAR(30)   NOT NULL,
  GAUGE_TYPE            VARCHAR(1),
  RAILWAYZONE           VARCHAR(30),
  PRIMARY KEY(STATION_ID));
 
CREATE TABLE TRAIN
( GENERALSEATS        INT          NOT NULL,  
  DURATION            TIME         NOT NULL,
  SOURCE              VARCHAR(6)   NOT NULL,
  DESTINATION         VARCHAR(6)   NOT NULL,
  TRAINTYPE           VARCHAR(20),
  TRAINNO             INT          NOT NULL,
  DISTANCE            INT          NOT NULL,
  ACSEATS             INT,
  PRIMARY KEY(TRAINNO),
  CHECK(SOURCE!=DESTINATION));
CREATE TABLE TICKET
( AGENT_ID             INT         NOT NULL,
  USER_ID              INT         NOT NULL,
  SOURCE               VARCHAR(6)  NOT NULL,
  DESTINATION          VARCHAR(6)  NOT NULL,
  PREGNANT             BOOLEAN,
  SR_CITIZEN           BOOLEAN,
  BERTH                INT         NOT NULL,
  COACH                VARCHAR(3)  NOT NULL,                
  PNR_NO               VARCHAR(10)        NOT NULL,
  TRAIN_NO             INT         NOT NULL,
  DATEOFTRAVEL         DATE        NOT NULL,
  PRIMARY KEY(PNR_NO),
  FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY(USER_ID)  REFERENCES USERS(USER_ID) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY(SOURCE) REFERENCES STATION(STATION_ID) ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE USERS
( USER_ID              INT         NOT NULL,
  FNAME                VARCHAR(30) NOT NULL,
  MNAME                VARCHAR(30),
  LNAME                VARCHAR(30) NOT NULL,
  PASSWORD             VARCHAR(10) NOT NULL, 
  DOB                  DATE        NOT NULL,
  SEX                  VARCHAR(10) NOT NULL,
  ADDR                 TEXT        NOT NULL,
  PHONE                INT         NOT NULL,
  SMARTCARDBALANCE     INT         NOT NULL,
  CARD_DETAILS         INT,
  OFFER_POINTS         INT         NOT NULL,
  PRIMARY KEY(USER_ID));
CREATE TABLE GOODS
( TRAIN_NO             INT         NOT NULL,
  DESTINATION          VARCHAR(6)  NOT NULL,
  SOURCE               VARCHAR(6)  NOT NULL,
  WEIGHT               INT         NOT NULL,
  TPNR_NO              VARCHAR(10)         NOT NULL,
  PRIMARY KEY(TPNR_NO),
  FOREIGN KEY(TPNR_NO) REFERENCES TICKET(PNR_NO) ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE FOODNDRINK
( TRANSACTION_DETAIL   INT         NOT NULL,
  TRAIN_NO             INT         NOT NULL,
  NAME                 VARCHAR(50) NOT NULL,
  BERTH                INT         NOT NULL,
  PNR_NO               VARCHAR(10)         NOT NULL,
  PRIMARY KEY(TRANSACTION_DETAIL,PNR_NO),
  FOREIGN KEY(PNR_NO) REFERENCES TICKET(PNR_NO) ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE AGENT
( AGENT_ID             INT          NOT NULL,
  PASSWORD             VARCHAR(10)  NOT NULL,
  NAME                 VARCHAR(50)  NOT NULL,
  DOB                  DATE         NOT NULL,
  COMMISION            FLOAT(2)     NOT NULL,
  PRIMARY KEY(AGENT_ID));
CREATE TABLE ARRIVES_AT
( STATION_ID            VARCHAR(6)  NOT NULL,
  TRAIN_NO              INT         NOT NULL,
  PRIMARY KEY(STATION_ID,TRAIN_NO),
  FOREIGN KEY(STATION_ID) REFERENCES STATION(STATION_ID) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY(TRAIN_NO) REFERENCES  TRAIN(TRAINNO) ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE  DEPARTS_FROM
( STATION_ID            VARCHAR(6)  NOT NULL,
  TRAIN_NO              INT         NOT NULL,
  PRIMARY KEY(STATION_ID,TRAIN_NO),
  FOREIGN KEY(STATION_ID) REFERENCES STATION(STATION_ID) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY(TRAIN_NO) REFERENCES  TRAIN(TRAINNO) ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE NON_USERS
( BOOKING_AGENT_ID      INT           NOT NULL,
  NAME                  VARCHAR(50)   NOT NULL,
  AGE                   INT           NOT NULL,
  DOB                   DATE          NOT NULL,
  PHONE                 INT           NOT NULL,
  ADDR                  TEXT          NOT NULL,
  PRIMARY KEY(NAME,PHONE),
  FOREIGN KEY(BOOKING_AGENT_ID) REFERENCES  AGENT(AGENT_ID) ON DELETE SET NULL ON UPDATE CASCADE);   

 