SELECT AGENT_ID
FROM AGENT
WHERE NAME!=PASSWORD;

SELECT STATION_ID,NAME
FROM STATION
WHERE RAILWAYZONE='NCR';

SELECT U.NAME,A.NAME
FROM NON_USERS AS U,AGENT AS A
WHERE U.BOOKING_AGENT_ID=A.AGENT_ID AND A.AGENT_ID=100;
/*
SELECT U.FNAME,T.DATEOFTRAVEL
FROM USERS AS U,TICKET AS T
WHERE U.USER_ID=T.USER_ID AND T.DATEOFTRAVEL LIKE '____04___';
*/
SELECT U.FNAME,F.TRANSACTION_DETAIL
FROM USERS AS U, FOODNDRINK AS F,TICKET AS T
WHERE  T.USER_ID=U.USER_ID AND F.PNR_NO=T.PNR_NO;

SELECT TRAIN_NAME,TRAINNO
FROM TRAIN
WHERE DESTINATION='HWH';

SELECT SOURCE,DESTINATION
FROM GOODS
WHERE WEIGHT>=500;

SELECT A.NAME,U.FNAME,T.PNR_NO
FROM AGENT AS A,USERS AS U,TICKET AS T
WHERE T.AGENT_ID=A.AGENT_ID AND T.USER_ID=A.AGENT_ID AND T.PNR_NO='1239870456';

SELECT T.TRAIN_NO,A.AGENT_ID
FROM TICKET AS T,AGENT AS A
WHERE T.AGENT_ID=A.AGENT_ID AND A.NAME='sahazeer' ;

SELECT T.COACH,F.BERTH
FROM TICKET AS T,FOODNDRINK AS F
WHERE F.PNR_NO=T.PNR_NO AND F.TRANSACTION_DETAIL=1002;